# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [4]:
import random as rd
import numpy as np
arrlist=[rd.randint(1,20) for i in range (25)]

# Create a (5, 5) array with random integers between 1 and 20
arr = np.array(arrlist).reshape(5,5)

print(arr)
arr[:,2]=1
print(f"new arr,{arr}")


[[ 3  9 11 10 19]
 [16  8 15 15 20]
 [ 8  3 12  2 11]
 [10 11 12 12  9]
 [18  7  2  1 11]]
new arr,[[ 3  9  1 10 19]
 [16  8  1 15 20]
 [ 8  3  1  2 11]
 [10 11  1 12  9]
 [18  7  1  1 11]]


In [8]:
#ans 1- second method
import numpy as np
arr=np.random.randint(1,20,size=(5,5))
print(arr)
arr[:,2]=1
print(f"new array is {arr}")

[[[ 1  9 15]
  [ 7 14 18]
  [12  4 10]]

 [[ 8  8 16]
  [ 7 15 15]
  [ 1 12 10]]]
new array is [[[ 1  9 15]
  [ 7 14 18]
  [ 1  1  1]]

 [[ 8  8 16]
  [ 7 15 15]
  [ 1  1  1]]]


In [1]:
#ans 2 - 
import numpy as np
arr=np.arange(1,37).reshape(6,6)
np.fill_diagonal(arr, 0)
print("Modified array:")
print(arr)



Modified array:
[[ 0  2  3  4  5  6]
 [ 7  0  9 10 11 12]
 [13 14  0 16 17 18]
 [19 20 21  0 23 24]
 [25 26 27 28  0 30]
 [31 32 33 34 35  0]]


In [ ]:
#ans 3 - 
import numpy as np
arr=np.random.randint(1,100,size=(5,5))
arr2=arr[2:4,1:3]
print(arr)
print(f"arr2={arr2}")

In [2]:
#ans 3.1-
import numpy as np
arr1=np.random.randint(1,100,size=(3,4))
arr2=np.random.randint(1,100,size=(3,4))
add=arr1+arr2
sub=arr1-arr2
mul=arr1*arr2
div=arr1/arr2
print(add)
print(sub)
print(mul)
print(div)

[[ 92  33  94 150]
 [103  81  56  81]
 [107 139 111 160]]
[[  8  29 -56  16]
 [-53  59 -46 -57]
 [-89  39 -23  14]]
[[2100   62 1425 5561]
 [1950  770  255  828]
 [ 882 4450 2948 6351]]
[[ 1.19047619 15.5         0.25333333  1.23880597]
 [ 0.32051282  6.36363636  0.09803922  0.17391304]
 [ 0.09183673  1.78        0.65671642  1.19178082]]


In [7]:
#ans 3.2 -
import numpy as np
arr=np.arange(1,17).reshape(4,4)
row_wise=np.sum(arr,axis=0)
column_wise=np.sum(arr,axis=1)
print(row_wise)
print(column_wise)

[28 32 36 40]
[10 26 42 58]


In [8]:
#ans 4.1-
import numpy as np
arr1=np.random.randint(1,100,size=(5,5))
arr2=np.random.randint(1,100,size=(5,5))
mean=np.mean(arr1)
std_dev=np.std(arr1)
variance=np.var(arr1)
print(mean)
print(std_dev)
print(variance)

45.0
30.01333037168651
900.8


In [12]:
# ans 4.2-
arr=np.arange(9).reshape(3,3)
std_dev=np.std(arr)
mean=np.mean(arr)
normalised=(arr - mean) / std_dev
print(arr)
print(std_dev)
print(mean)
normalised_mean=np.mean(normalised)
print(normalised)
print(normalised_mean)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2.581988897471611
4.0
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
0.0


In [ ]:
# Create a NumPy array of shape (3, 3) representing a matrix
import numpy as np
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)